version: "3.7"
networks:
  backend:
    driver: bridge

services:
  centrifugo:
    image: 'centrifugo/centrifugo:v2.6.1'
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c config.json
    ports:
      - '9005:9005'
    networks:
      - backend
    ulimits:
        nofile:
          soft: "65536"
          hard: "65536"

  redis:
    image: 'redis:6.0.6-alpine'
    volumes:
      - ./redis/data/:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    ports:
      - '6379'
    networks:
      - backend
