global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'centrifugo'
    metrics_path: /metrics
    static_configs:
    - targets: ['centrifugo:8000']

  - job_name: 'redis_exporter'
    static_configs:
    - targets: ['redis_exporter:9121']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['node_exporter:9100']
