{
 "title": "Centrifugo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "centrifuge_node_messages_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(centrifuge_node_messages_received_count[5m])",
     "legendFormat": "{{job}}-{{type}}"
    }
   ]
  },
  {
   "title": "centrifuge_node_num_clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "centrifuge_node_num_clients", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "centrifuge_node_messages_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(centrifuge_node_messages_received_count[5m])",
     "legendFormat": "{{job}}-{{type}}"
    }
   ]
  },
  {
   "title": "centrifuge_node_num_users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "centrifuge_node_num_users", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "centrifuge_node_messages_sent_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(centrifuge_node_messages_sent_count[5m])",
     "legendFormat": "{{job}}-{{type}}"
    }
   ]
  },
  {
   "title": "centrifuge_node_build",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "centrifuge_node_build", "legendFormat": "{{job}}-{{version}}" }
   ]
  },
  {
   "title": "centrifuge_node_num_channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "centrifuge_node_num_channels", "legendFormat": "centrifuge_node_num_channels" }
   ]
  }
 ]
}